apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: node-deployment
  ports:
    - protocol: 'TCP'
      port: 3000
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-first-app-deploymemt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-deployment
      tier: backend
  template:
    metadata:
      labels:
        app: node-deployment
        tier: backend
    spec:
      containers:
        - name: app-node-container
          image: gabezy/kube-first-app:2
          livenessProbe: 
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5